// Code generated by "stringer -type=TokType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeEof-0]
	_ = x[TypeEol-1]
	_ = x[TypeComma-2]
	_ = x[TypeColon-3]
	_ = x[TypeSemicolon-4]
	_ = x[TypeLParen-5]
	_ = x[TypeRParen-6]
	_ = x[TypeLBrace-7]
	_ = x[TypeRBrace-8]
	_ = x[TypeLBracket-9]
	_ = x[TypeRBracket-10]
	_ = x[TypeDefConst-11]
	_ = x[TypeDefVar-12]
	_ = x[TypeAssign-13]
	_ = x[TypeAdd-14]
	_ = x[TypeSub-15]
	_ = x[TypeMul-16]
	_ = x[TypeDiv-17]
	_ = x[TypeMod-18]
	_ = x[TypeEq-19]
	_ = x[TypeNeq-20]
	_ = x[TypeLess-21]
	_ = x[TypeGreat-22]
	_ = x[TypeLeq-23]
	_ = x[TypeGeq-24]
	_ = x[TypeDot-25]
	_ = x[TypeQuestion-26]
	_ = x[TypeIf-27]
	_ = x[TypeElse-28]
	_ = x[TypeSwitch-29]
	_ = x[TypeCase-30]
	_ = x[TypeLoop-31]
	_ = x[TypeSkip-32]
	_ = x[TypeBreak-33]
	_ = x[TypeReturn-34]
	_ = x[TypeNot-35]
	_ = x[TypeAnd-36]
	_ = x[TypeOr-37]
	_ = x[TypeTrue-38]
	_ = x[TypeFalse-39]
	_ = x[TypeNil-40]
	_ = x[TypeIdentifier-41]
	_ = x[TypeInteger-42]
	_ = x[TypeFloat-43]
	_ = x[TypeString-44]
}

const _TokType_name = "TypeEofTypeEolTypeCommaTypeColonTypeSemicolonTypeLParenTypeRParenTypeLBraceTypeRBraceTypeLBracketTypeRBracketTypeDefConstTypeDefVarTypeAssignTypeAddTypeSubTypeMulTypeDivTypeModTypeEqTypeNeqTypeLessTypeGreatTypeLeqTypeGeqTypeDotTypeQuestionTypeIfTypeElseTypeSwitchTypeCaseTypeLoopTypeSkipTypeBreakTypeReturnTypeNotTypeAndTypeOrTypeTrueTypeFalseTypeNilTypeIdentifierTypeIntegerTypeFloatTypeString"

var _TokType_index = [...]uint16{0, 7, 14, 23, 32, 45, 55, 65, 75, 85, 97, 109, 121, 131, 141, 148, 155, 162, 169, 176, 182, 189, 197, 206, 213, 220, 227, 239, 245, 253, 263, 271, 279, 287, 296, 306, 313, 320, 326, 334, 343, 350, 364, 375, 384, 394}

func (i TokType) String() string {
	if i >= TokType(len(_TokType_index)-1) {
		return "TokType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokType_name[_TokType_index[i]:_TokType_index[i+1]]
}
